version: "3.9"

services:
  mysql-test:
    image: mysql:8
    container_name: mysql-test
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: studentdb
    ports:
      - "3306:3306"
    networks:
      - student-network

  app:
    build: .
    container_name: student-app
    depends_on:
      - mysql-test
    ports:
      - "8089:8089"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-test:3306/studentdb?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_DATASOURCE_INITIALIZATION_MODE: always
    networks:
      - student-network

networks:
  student-network:
